
version: 2

models:
  - name: hotness_score
    description: "Hotness score, mix of timeliness and popularity for songs"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - song
            - artist
